import _ from "lodash";
import { IGameArrayType } from "@/model/game";

const sumArr = (arr: string[]) => {
  return arr.reduce((sum: number, current: any) => {
    sum += Number(current);
    return sum;
  }, 0);
};

//判断同号

export const gameArray: IGameArrayType[] = [
  {
    type: "yuxx",
    layout: 18,
    tabel: [
      {
        name: [1],
        odds: 1.98,
        winFn: (e) => e.includes(String(1)),
        num: "1",
        lname: "yuxx",
        type: "YTH",
        type_text: "一同号",
      },
      {
        name: [2],
        odds: 1.98,
        winFn: (e) => e.includes(String(2)),
        num: "2",
        lname: "yuxx",
        type: "YTH",
        type_text: "一同号",
      },
      {
        name: [3],
        odds: 1.98,
        winFn: (e) => e.includes(String(3)),
        num: "3",
        lname: "yuxx",
        type: "YTH",
        type_text: "一同号",
      },
      {
        name: [4],
        odds: 1.98,
        winFn: (e) => e.includes(String(4)),
        num: "4",
        lname: "yuxx",
        type: "YTH",
        type_text: "一同号",
      },
      {
        name: [5],
        odds: 1.98,
        winFn: (e) => e.includes(String(5)),
        num: "5",
        lname: "yuxx",
        type: "YTH",
        type_text: "一同号",
      },
      {
        name: [6],
        odds: 1.98,
        winFn: (e) => e.includes(String(6)),
        num: "6",
        lname: "yuxx",
        type: "YTH",
        type_text: "一同号",
      },
      {
        name: [1, 1],
        odds: 12.88,
        winFn: (e) => e.filter((i) => i == "1").length == 2,
        num: "11",
        lname: "yuxx",
        type: "ETH",
        type_text: "二同号",
      },
      {
        name: [2, 2],
        odds: 12.88,
        winFn: (e) => e.filter((i) => i == "2").length == 2,
        num: "22",
        lname: "yuxx",
        type: "ETH",
        type_text: "二同号",
      },
      {
        name: [3, 3],
        odds: 12.88,
        winFn: (e) => e.filter((i) => i == "3").length == 2,
        num: "33",
        lname: "yuxx",
        type: "ETH",
        type_text: "二同号",
      },
      {
        name: [4, 4],
        odds: 12.88,
        winFn: (e) => e.filter((i) => i == "4").length == 2,
        num: "44",
        lname: "yuxx",
        type: "ETH",
        type_text: "二同号",
      },
      {
        name: [5, 5],
        odds: 12.88,
        winFn: (e) => e.filter((i) => i == "5").length == 2,
        num: "55",
        lname: "yuxx",
        type: "ETH",
        type_text: "二同号",
      },
      {
        name: [6, 6],
        odds: 12.88,
        winFn: (e) => e.filter((i) => i == "6").length == 2,
        num: "66",
        lname: "yuxx",
        type: "ETH",
        type_text: "二同号",
      },
    ],
  },
  {
    type: "yuxx",
    layout: 18,
    tabel: [
      {
        name: [1, 2],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("12"),
        num: "12",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [1, 3],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("13"),
        num: "13",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [1, 4],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("14"),
        num: "14",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [1, 5],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("15"),
        num: "15",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [1, 6],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("16"),
        num: "16",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [2, 3],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("23"),
        num: "23",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [2, 4],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("24"),
        num: "24",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [2, 5],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("25"),
        num: "25",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [2, 6],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("26"),
        num: "26",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [3, 4],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("34"),
        num: "34",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [3, 5],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("35"),
        num: "35",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [3, 6],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("36"),
        num: "36",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [4, 5],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("45"),
        num: "45",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [4, 6],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("46"),
        num: "46",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
      {
        name: [5, 6],
        odds: 6.98,
        winFn: (e) => _.orderBy(e).join("").includes("56"),
        num: "56",
        lname: "yuxx",
        type: "EBT",
        type_text: "二不同",
      },
    ],
  },
];
