import _ from "lodash";
import { IGameArrayType } from "@/model/game";
import i18n from "@/lang/i18n";

//判断同号

export const gameArray: IGameArrayType[] = [
  {
    type: i18n.t("feitingType0"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 0) > 5,
        num: "1,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 0) < 6,
        num: "1,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("long"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 0) > _.nth(e, 9),
        num: "1,龙",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("hu"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 0) < _.nth(e, 9),
        num: "1,虎",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 0) % 2 === 1,
        num: "1,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 0) % 2 === 0,
        num: "1,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType1"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 1) > 5,
        num: "2,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 1) < 6,
        num: "2,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("long"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 1) > _.nth(e, 8),
        num: "2,龙",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("hu"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 1) < _.nth(e, 8),
        num: "2,虎",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 1) % 2 === 1,
        num: "2,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 1) % 2 === 0,
        num: "2,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType2"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 2) > 5,
        num: "3,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 2) < 6,
        num: "3,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("long"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 2) > _.nth(e, 7),
        num: "3,龙",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("hu"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 2) < _.nth(e, 7),
        num: "3,虎",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 2) % 2 === 1,
        num: "3,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 2) % 2 === 0,
        num: "3,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType3"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 3) > 5,
        num: "4,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 3) < 6,
        num: "4,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("long"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 3) > _.nth(e, 6),
        num: "4,龙",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("hu"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 3) < _.nth(e, 6),
        num: "4,虎",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 3) % 2 === 1,
        num: "4,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 3) % 2 === 0,
        num: "4,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType4"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 4) > 5,
        num: "5,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 4) < 6,
        num: "5,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("long"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 4) > _.nth(e, 5),
        num: "5,龙",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("hu"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 4) < _.nth(e, 5),
        num: "5,虎",
        lname: "xyft",
        type: "LH",
        type_text: "龙虎斗",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 4) % 2 === 1,
        num: "5,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 4) % 2 === 0,
        num: "5,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType5"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 5) > 5,
        num: "6,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 5) < 6,
        num: "6,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 5) % 2 === 1,
        num: "6,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 5) % 2 === 0,
        num: "6,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType6"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 6) > 5,
        num: "7,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 6) < 6,
        num: "7,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 6) % 2 === 1,
        num: "7,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 6) % 2 === 0,
        num: "7,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType7"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 7) > 5,
        num: "8,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 7) < 6,
        num: "8,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 7) % 2 === 1,
        num: "8,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 7) % 2 === 0,
        num: "8,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType8"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 8) > 5,
        num: "9,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 8) < 6,
        num: "9,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 8) % 2 === 1,
        num: "9,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 8) % 2 === 0,
        num: "9,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
  {
    type: i18n.t("feitingType9"),
    layout: 0,
    tabel: [
      {
        name: i18n.t("da"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 9) > 5,
        num: "10,大",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("xiao"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 9) < 6,
        num: "10,小",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("dan"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 9) % 2 === 1,
        num: "10,单",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
      {
        name: i18n.t("shuang"),
        odds: 1.92,
        winFn: (e) => _.nth(e, 9) % 2 === 0,
        num: "10,双",
        lname: "xyft",
        type: "HE",
        type_text: "和值",
      },
    ],
  },
];
